### ISSUE TITLE
broken dockerfile for binary build

### ISSUE THREAD

**Issue by Tobi-De** [Tobi-De/falco_tailwind#79]

**Comment by Tobi-De** [comment]
I'm closing this for now, the local binary build only fails on my computer (fedora 40), on my work laptop (macos) and on cofin ubuntu it works too, the issue is specific to my computer.

````shell
error: failed to run custom build command for `pyapp v0.23.0`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installVk9TzN/release/build/pyapp-6ccd85b786b5a516/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-env=PYAPP_PROJECT_DEPENDENCY_FILE=
  cargo:rustc-env=PYAPP__PROJECT_DEPENDENCY_FILE_NAME=
  cargo:rustc-env=PYAPP_PROJECT_NAME=blaze
  cargo:rustc-env=PYAPP_PROJECT_VERSION=0.0.1
  cargo:rustc-env=PYAPP__PROJECT_EMBED_FILE_NAME=blaze-0.0.1-py3-none-any.whl

  --- stderr
  thread 'main' panicked at /home/tobi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyapp-0.23.0/build.rs:547:14:
  called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: TimedOut }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to compile `pyapp v0.23.0`, intermediate artifacts can be found at `/tmp/cargo-installVk9TzN`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/tobi/.local/share/hatch/env/pip-compile/blaze/b7ma27ZR/blaze-build/lib/python3.12/site-packages/hatchling/__main__.py", line 6, in <module>
    sys.exit(hatchling())
             ^^^^^^^^^^^
  File "/home/tobi/.local/share/hatch/env/pip-compile/blaze/b7ma27ZR/blaze-build/lib/python3.12/site-packages/hatchling/cli/__init__.py", line 26, in hatchling
    command(**kwargs)
  File "/home/tobi/.local/share/hatch/env/pip-compile/blaze/b7ma27ZR/blaze-build/lib/python3.12/site-packages/hatchling/cli/build/__init__.py", line 82, in build_impl
    for artifact in builder.build(
  File "/home/tobi/.local/share/hatch/env/pip-compile/blaze/b7ma27ZR/blaze-build/lib/python3.12/site-packages/hatchling/builders/plugin/interface.py", line 155, in build
    artifact = version_api[version](directory, **build_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tobi/.local/share/hatch/env/pip-compile/blaze/b7ma27ZR/blaze-build/lib/python3.12/site-packages/hatchling/builders/binary.py", line 163, in build_bootstrap
    self.cargo_build(install_command, cwd=context_dir, env=env)
  File "/home/tobi/.local/share/hatch/env/pip-compile/blaze/b7ma27ZR/blaze-build/lib/python3.12/site-packages/hatchling/builders/binary.py", line 195, in cargo_build
    raise OSError(message)
OSError: Compilation failed (code 101)

```
